# Generated by Django 4.1.3 on 2022-12-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('bid', models.FloatField(default=0)),
                ('img_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
