# Generated by Django 4.1.3 on 2023-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_time_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
